name: cs236781-miniproject
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # common
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-xdist
  - python=3.8.12
  - scikit-learn
  - scipy
  - pytorch
  - cudatoolkit
  - torchvision
  - torchtext
  - h5py
  - scikit-image
  
